# Generated by Django 4.2.3 on 2023-08-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
