# Generated by Django 4.2.3 on 2023-08-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_ticket_respuesta_alter_ticket_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
